token_is_invalid = "Пожалуйста зарегистрируйтесь и залогиньтесь"
u_have_not_enough_rights = "У вас не достаточно прав, чтобы выполнить операцию"
wrong_password_or_login = "Вы ввели неверный логин либо пароль"
this_user_already_exist = "Такой пользователь уже существует"
server_error = "Упссс... Вы положили сервер :("