"""fourth

Revision ID: f462a7191678
Revises: 6f113d5aecd6
Create Date: 2025-01-06 03:04:51.977206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f462a7191678'
down_revision: Union[str, None] = '6f113d5aecd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sessions')
    op.drop_table('menus')
    op.drop_table('user_table_association')
    op.drop_table('users')
    op.drop_table('tables')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('max_guest_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tables_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tables_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('user_role', postgresql.ENUM('AUTHORIZED_USER', 'ADMIN', name='roles'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email_address', name='users_email_address_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_table_association',
    sa.Column('order_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('guest_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extra_wishes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_free', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='user_table_association_table_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_table_association_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_table_association_pkey')
    )
    op.create_table('menus',
    sa.Column('food_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('food_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('food_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('food_type', postgresql.ENUM('MEAT_DISHES', 'SNACKS', 'DESSERTS', 'DRINKS', 'SOUPS', name='food_types'), autoincrement=False, nullable=True),
    sa.Column('food_photo_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='menus_pkey'),
    sa.UniqueConstraint('food_name', name='menus_food_name_key'),
    sa.UniqueConstraint('food_photo_path', name='menus_food_photo_path_key')
    )
    op.create_table('Sessions',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expire_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='Sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Sessions_pkey'),
    sa.UniqueConstraint('user_id', name='Sessions_user_id_key')
    )
    # ### end Alembic commands ###
